export const CONSTANT_MAX_SIZE_IMAGE_UPLOAD = 5 * 1024 * 1024;
export const CONSTANT_MAX_LENGTH_IMAGE_UPLOAD = 10;

export const CONSTANT_MAX_SIZE_VIDEO_UPLOAD = 10 * 1024 * 1024;
export const CONSTANT_MAX_LENGTH_VIDEO_UPLOAD = 2;
